#!/usr/bin/perl

# $Header: /home/cvs/thundaural/checkdeps,v 1.14 2004/06/10 05:57:38 jukebox Exp $

# just a little quick and dirty script to help you make sure you have all the 
# dependancies installed.  It should really be better than this.  lots of code 
# duplication here

# and it should really generate settings/config files for the optional portions

use Data::Dumper;
use Getopt::Long;

$| = 1;

my $check_client = 0;
my $check_server = 0;
my $softfail = 0;

my $prfailed = 0;
my $server_found_progs = {};

my %options = (
	'client!'=>\$check_client,
	'server!'=>\$check_server,
	'softfail!'=>\$softfail,
);

&usage unless GetOptions(%options);

sub usage {
	print STDERR "Usage: $0 [--client] [--server] [--softfail]\n";
	exit 1;
}

if (!$check_client && !$check_server) {
	$check_client = 1;
	$check_server = 1;
}

sub mydie {
	my $msg = shift;
	if ($msg) {
		$msg .= "\n" if ($msg !~ m/\n$/);
		if ($softfail) {
			warn("\n*** $msg");
			$prfailed = 1;
		} else {
			die("\n*** $msg");
		}
	} else {
		print " ok\n";
	}
}

use Config;

if ($check_server) {
	print "\nChecking dependancies for server...\n";
	&checking("threaded perl");
	$Config{useithreads} or &mydie("this program requires a threaded perl (ithreads)\n");
	&ok;

	my @modules = qw/DBI DBD::SQLite File::Basename Socket IO::Socket
	IO::Socket::INET IO::Select threads threads::shared
	Thread::Queue LWP LWP::UserAgent XML::Ximple Data::Dumper
	CDDB_get Ogg::Vorbis::Decoder Audio::Mad MP3::Info IO::File
	Audio::DSP Audio::Wav
	/;

	foreach my $mod (@modules) {
		&checking('perl module', $mod);
		&havemodule($mod) or &mydie("unable to locate module $mod");
		&ok;
	}

	my %dirs = (
		'/home/storage' => 'general storage directory',
		'/home/storage/db' => 'storage for SQLite database',
	);

	foreach my $dir (keys %dirs) {
		&checking("", $dirs{$dir});
		(-d $dir) || &mydie("unable to find directory $dir\n");
		&ok;

		&checking("accessiblity of", sprintf("%s (%s)", $dirs{$dir}, $dir));
		my $x = `cd $dir > /dev/null 2>/dev/null ; echo \$?`;
		$x += 0;
		&mydie("unable to cd to $dir") if ($x);
		open(X, ">$dir/thundauralxxx.$$.tmp") || &mydie("unable to write to $dir");
		close(X);
		unlink("$dir/thundauralxxx.$$.tmp");
		opendir(X, $dir) || &mydie("unable to open $dir for reading\n");
		readdir(X) || &mydie("unable to get directory listing of $dir\n");
		closedir(X);
		&ok;
	}

	my @programs = (
		{ 'for'=>'ripping audio', 'type'=>'oneof', 'list'=>['dagrab', 'cdda2wav', 'cdparanoia'] },
		{ 'for'=>'audio info extracting', 'type'=>'must', 'list'=>'cdda2wav' },
		# --version doesn't work for cdda2wav version 1, but --help does work on both
		{ 'for'=>'cdda2wav version', 'type'=>'grep', 'pattern'=>'^Version 2', 'list'=>'cdda2wav --help 2>&1' },
		{ 'for'=>'changing the volume', 'label'=>'aumix', 'type'=>'oneof', 'list'=>['aumix-minimal', 'aumix'] },
		{ 'for'=>'encoding audio', 'type'=>'must', 'list'=>'oggenc' },
		{ 'for'=>'determining device usage', 'type'=>'must', 'list'=>'fuser' },
		{ 'for'=>'downloading cover art', 'type'=>'must', 'list'=>'php' },
	);

	NEXTPROG:
	foreach my $prog (@programs) {
		my $for = $prog->{'for'};
		my $type = $prog->{'type'};
		my $label = $prog->{'label'};
		if ($type eq 'oneof') {
			my $list = $prog->{'list'};
			my $found = 0;
			foreach my $p (@{$list}) {
				&checking('program', $p);
				if (my $where = &haveprogram($p)) {
					&ok($where);
					if (defined($label) && $label) {
						$server_found_progs->{$label} = $where;
					} else {
						$server_found_progs->{$p} = $where;
					}
					$found++;
					#next NEXTPROG;
				} else {
					$server_found_progs->{"# $p was not found"} = $p;
					print " unable to find $p\n";
				}
			}
			&mydie("unable to locate one of ".join(', ', @{$list})." (used for $for) in path\n")
				if (!$found);
		} elsif ($type eq 'grep') {
			&checking('', $prog->{'for'});
			my $pat = $prog->{'pattern'};
			my $prog = $prog->{'list'};
			my $cdda2wavpath = $server_found_progs->{'cdda2wav'};
			$prog =~ s/cdda2wav/$cdda2wavpath/g;
			my @x = `$prog`;
			my @y = grep(/$pat/, @x);
			if (@y) {
				my $msg = shift @y;
				chomp $msg;
				&ok($msg);
			} else {
				&mydie("it doesn't look like cdda2wav is version 2\n");
			}
			next NEXTPROG;
		} elsif ($type eq 'must') {
			my $for = $prog->{'for'};
			my $prog = $prog->{'list'};
			&checking("program used for $for", $prog);
			my $where;
			($where = &haveprogram($prog)) or &mydie("unable to locate $prog (used for $for) in path\n");
			$server_found_progs->{$prog} = $where;
			&ok($where);
		} elsif ($type eq 'optional') {
			my $for = $prog->{'for'};
			my $prog = $prog->{'list'};
			&checking("program used for $for", $prog);
			my $where;
			if ($where = &haveprogram($prog)) {
				$server_found_progs->{$prog} = $where;
				&ok($where);
			} else {
				warn("unable to locate $prog (used for $for) in path\n");
			}
		} else {
			die("unknown program type \"$type\"");
		}
	}

	my @files = qw!
		/usr/local/lib/php/AmazonSearch.php
		/usr/local/lib/php/class.nusoap_base.php
		/usr/local/lib/php/class.soapclient.php
		/usr/local/lib/php/class.soap_fault.php
		/usr/local/lib/php/class.soap_parser.php
		/usr/local/lib/php/class.soap_server.php
		/usr/local/lib/php/class.soap_transport_http.php
		/usr/local/lib/php/class.soap_val.php
		/usr/local/lib/php/class.wsdl.php
		/usr/local/lib/php/class.xmlschema.php
		/usr/local/lib/php/nusoap.php
	!;
	foreach my $f (@files) {
		&checking('php lib file', $f);
		if (!-s $f) {
			mydie("please copy the contents of server/usr-local-lib-php to /usr/local/lib/php");
			last;
		}
		&ok;
	}

#	open(T, ">TAProgramLocations.pm") || die("unable to open TAProgramLocations.pm for writing\n");
#	print T "package TAProgramLocations;\n";
#	print T "# this file is automaticly generated by checkdeps\n\n";
#	foreach my $p (keys %{$server_found_progs}) {
#		my $px = $p;
#		$px =~ s/\W/_/g;
#		printf T 'sub %s { \'%s\'; }', $px, $server_found_progs->{$p};
#		print T "\n";
#	}
#	print T "\n1;\n";
#	print T "\n\n__END__\n\n";
#	foreach my $p (keys %{$server_found_progs}) {
#		my $px = $p;
#		$px =~ s/\W/_/g;
#		printf T 'PROG_%s=%s', (uc $px), $server_found_progs->{$p};
#		print T "\n";
#	}
#	close(T);

	&write_config_file();
}


if ($check_client) {
	print "\nChecking dependancies for client...\n";

	# I ripped this code out of Makefile.linux in the SDL_perl distribution
	my @dirs=(
		'/usr/local/include/SDL',
		'/usr/local/include',
		'/usr/include/SDL',
		'/usr/include',
	);

	# stupid little hack to get them to be checked in the order I designate
	my %ext = (
		# all my gfx come in PNG format
		x1_png=>{inc=>'HAVE_PNG', test=>'png.h', srcpage=>'http://www.rpmfind.net/linux/rpm2html/search.php?query=libpng'},
		# for good measure (coverart is usually in jpeg format)
		x2_jpeg=>{inc=>'HAVE_JPEG',test=>'jpeglib.h',srcpage=>'http://www.rpmfind.net/linux/rpm2html/search.php?query=libjpeg'}, 
		x3_SDL=>{ inc =>'HAVE_SDL', test=>'SDL.h',srcpage=>'http://www.libsdl.org/download-1.2.php'},
		x4_SDL_image=>{inc=>'HAVE_SDL_IMAGE', test=>'SDL_image.h', srcpage=>'http://www.libsdl.org/projects/SDL_image/'},
		x4_SDL_ttf=>{inc=>'HAVE_SDL_TTF',test=>'SDL_ttf.h',srcpage=>'http://www.libsdl.org/projects/SDL_ttf/'},
		x4_SDL_gfx=>{inc=>'HAVE_SDL_GFX',test=>'SDL_gfxPrimitives.h',srcpage=>'http://www.ferzkopp.net/~aschiffler/Software/SDL_gfx-2.0/'},
	);      

	for my $e ( sort keys %ext ) {
		for my $d (@dirs) {
	        	$ext{$e}{exists} ||= -e "$d/$ext{$e}{test}"
		}
	}

	foreach my $e ( sort keys %ext ) {
		my $pe = $e; $pe =~ s/^x\d+_//;
		&checking('headers for library', $pe);
		if (!$ext{$e}->{'exists'}) {
			&mydie("Unable to locate $pe libraries and header files.  You can obtain source from ".$ext{$e}->{'srcpage'}."  Be sure to install any development related files (like -devel rpms)");
		}
		&ok;
	}

	&checking('perl module', 'SDL');
	&havemodule('SDL') or &mydie("Unable to locate module SDL.  Grab the necessary version 2.1.0 from the Thundaural website download section.");
	&ok;

	&checking('SDL perl version');
	eval "use SDL;";
	&mydie("Unable to locate SDL Perl.  Grab the necessary version 2.1.0 from the thundaural website download section.") if ($@ =~ m/^Can't locate/);
	&mydie("SDL Perl version must be 2.1.0.  Grab it from the thundaural website download section.") unless ($SDL::VERSION =~ /^2\.\d+\.\d+$/);
	&ok($SDL::VERSION);

	&checking('SDL perl supports event push');
	eval 'use SDL::Event; my $e = new SDL::Event; $e->push();';
	&mydie("Version of SDL Perl doesn't define SDL::Event::push.  Use version 2.1.0 from the thundaural download section.") if ($@ =~ m/Can't locate object method "push/);
	&ok("SDL::Event::push found");

	@modules = qw/SDL::Surface SDL::Constants 
	SDL::App SDL::Event SDL::Color SDL::Timer SDL::Font 
	SDL::TTFont SDL::Tool::Graphic SDL::Cursor IO::Socket IO::Socket::INET/;

	foreach my $mod (@modules) {
		&checking('perl module', $mod);
		&havemodule($mod) or &mydie("unable to locate module $mod");
		&ok;
	}

	my @programs = qw/ xscreensaver-command /;

	foreach my $prog (@programs) {
		&checking('program', $prog);
		&haveprogram($prog) or &mydie("unable to locate $prog");
		&ok;
	}
}

####

sub haveprogram {
	my $prog = shift;
	if (open(X, "which $prog 2>/dev/null |")) {
		my $where = <X>;
		chomp $where;
		close(X);
		my $r = $? >> 8;
		return $r == 1 ? 0 : $where;
	}
	return 0;
}


sub havemodule {
	my $mod = shift;
	eval "require($mod);";
	return $@ =~ m/^Can't locate/ ? 0 : 1;
}

sub checking {
	my $what = pop;
	my $type = shift;
	$type .= " " if ($type);
	print "  checking for $type$what...";
	$prfailed = 0;
}

sub ok {
	return if ($prfailed);
	if (@_) {
		my $msg = shift;
		print " $msg\n";
	} else {
		print " ok\n";
	}
}

sub write_config_file {

	my $preamble = <<'EOF';
# Thundaural Jukebox Configuration File
#
# Variable substitution occurs at configuration file read time for $VAR values
# ${VAR} is not variable substituted during read time, but are run-time substituted
 
# program locations, these should have been generated by the checkdeps script
EOF

	my $progs = '';
	
	foreach my $p (keys %{$server_found_progs}) {
		if ($p =~ m/^#/) {
			$progs .= "$p\n";
		} else {
			$progs .= sprintf('prog %s:%s%s', $p, $server_found_progs->{$p}, "\n");
		}
	}

	my $defaults = <<'EOF';
 
# order is important here -- storagedir and homedir must be defined
# before dbfile and cmd entries
 
# where the server stores everything, like the audio files and cover art, etc
storagedir /home/storage
# the location of the server script, and other support scripts
homedir .
 
# relative to storagedir if it doesn't begin with a /
dbfile db/data.db
 
# the address and port that the server should listen on
#listenhost localhost
listenport 9000
 
# the number of seconds to pause between songs
# this only applies to songs that are not in sequence on the same album
pausebetween 4
 
# list of all the devices, both playback (sound cards) and reading (cdrom drives)
# device-name:device-info
# where device-info can be for audio playback devices:
#     play=/dev/entry:mixer=/dev/entry
# or for cdrom drives:
#     read=/dev/entry
# order of defaults of the same type (play or read) is important -- the first
# one will determine the 'default' for that type
# in the case of playback devices, even though we'll send audio output to all
# the devices, we interact with all of them as a single logical device
 
device main:play=/dev/dsp:mixer=/dev/mixer
#device backup:play=/dev/dsp1:mixer=/dev/mixer1
 
device cdrom:read=/dev/cdrom
 
# relative to homedir if it doesn't begin with a /
cmd ripcdrom:ripdisc.pl --dbfile ${DBFILE} --device ${DEVICEFILE} --storagedir ${STORAGEDIR} ${PROGOPTS}
cmd volumeset:/usr/bin/aumix -d ${DEVICEFILE} -w100 -v${VOLUME}
cmd volumequery:/usr/bin/aumix -d ${DEVICEFILE} -q
EOF

	if (open(CONF, ">thundaural-server.conf")) {
		print CONF $preamble.$progs.$defaults;
		close(CONF);
	} else {
		die("unable to open thundaural-server.conf: $!\n");
	}

	print "*********************\n";
	print "You can move the thundaural-server.conf file to /etc/thundaural/server.conf,\n";
	print "into the server directory, or keep it here -- the server should be able to find it.\n";
	print "*********************\n";

}

#    Thundaural Jukebox
#    Copyright (C) 2003-2004  Andrew A. Bakun
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

